# appveyor file for kiidrv

# General Build Configuration
version: "{build}"

os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

# Build Setup
build:
  project: kiidrv.sln
  parallel: true
  verbosity: detailed


# Build Matrix
platform:
  - Win32
  - x64

configuration:
  - Debug
  - Release


# Build Dependencies
install:
  - curl -o libusbK-3.0.7.0-bin.7z -L "https://downloads.sourceforge.net/project/libusbk/libusbK-release/3.0.7.0/libusbK-3.0.7.0-bin.7z?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Flibusbk%2Ffiles%2FlibusbK-release%2F3.0.7.0%2FlibusbK-3.0.7.0-bin.7z%2Fdownload&ts=1516239099"
  - 7z x libusbK-3.0.7.0-bin.7z
  - dir


# Build Steps
build_script:
  - msbuild "kiidrv.sln" /m /t:Clean /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild "kiidrv.sln" /m /t:installer_x86 /p:BuildMacros="LIBUSBK_DIR=\"c:/projects/kiidrv/libusbK-3.0.7.0-bin/bin\"" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Platform=Win32
  - msbuild "kiidrv.sln" /m /t:installer_x64 /p:BuildMacros="LIBUSBK_DIR=\"c:/projects/kiidrv/libusbK-3.0.7.0-bin/bin\"" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Platform=x64
  - msbuild "kiidrv.sln" /m /t:kiidrv /p:BuildMacros="LIBUSBK_DIR=\"c:/projects/kiidrv/libusbK-3.0.7.0-bin/bin\"" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"


# Post Build Steps
after_build:
  - ps: move c:/projects/kiidrv/$env:platform/$env:configuration/examples/kiidrv.exe c:/projects/kiidrv/$env:platform/$env:configuration/examples/kiidrv-$env:platform-$env:configuration.exe


# Package Artifacts
artifacts:
  - path: '$(platform)/$(configuration)/examples/*.exe'


# Build Artifact Push (tagged releases only)
deploy:
  # GitHub Releases
  - provider: GitHub
    auth_token:
      secure: wjAvOOpKfKhMEDP/wXiAbGhXsk2XN6JJ0Ou/fotzTp8TUfmDb5afAHV8rD/Mlwn8
    artifact: /.*\.exe/, kiidrv/kiibohd.conf
    draft: true
    prerelease: false
    description: 'libwdi based libusbK automated driver installer'
    # Conditions for uploading release
    on:
      appveyor_repo_tag: true

# Post Build Commands
on_finish:
  - Tree /F

